exclude: ".git|.tox"
default_stages: [commit]
fail_fast: true

repos:
  - hooks:
      - id: commitizen
        stages: [commit-msg]
      - id: commitizen-branch
        stages:
          - push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.5.2
