site_name: TVSD
plugins:
  - mkdocstrings:
      handlers:
      python:
        options:
          docstring_options:
            ignore_init_summary: yes
          merge_init_into_class: yes
          show_submodules: no
  - search

theme:
  name: "material"
  features:
    - content.code.annotate
    - toc.integrate
    - navigation.top
